### ISSUE TITLE
Laravel 5.5 Compatibility

### ISSUE THREAD

**Issue by Shkeats** [spatie/laravel-partialcache#14]
Hi guys, 

Can you confirm or deny Laravel 5.5 compatibility for this package? I saw some work was being done in a fork to achieve this, and also some commits on master but not in the tagged releases.

If there's any work left to do, I'd be happy to help.

**Comment by freekmurze** [comment]
We don't use this package ourselves much anymore, so can't tell for sure.

Test it out. We'd probably accept a PR to make it L5.5 compatible if it's not.
