### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by sdebacker** [spatie/laravel-partialcache#2]
Hello Freek, I have this exception thrown, but I don’t know yet when and why. Do you see what is the problem ?

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()' in /home/forge/microstart.be/vendor/spatie/laravel-responsecache/src/ResponseCache.php:121
```

**Comment by freekmurze** [comment]
Am I correct in assuming that this issue should have posted on the laravel-responsecache issue tracker? :smile:

**Comment by sdebacker** [comment]
héhé yes

**Comment by freekmurze** [comment]
Moved the conversation to https://github.com/spatie/laravel-responsecache/issues/5
