### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Lambik** [spatie/laravel-partialcache#5]
Hi,

I have installed the tool as you say, and when I run through the PartialCacheServiceProvider with xdebug, I can see that the directive "cache" is correctly added.

However, when I then watch my view, which has this line in its body:

```
@cache('frontend.partials.category-tabs', ['id_partial' => 'home-category-tab'], 60)
```

The output in html just shows the "@cache" line instead of the contents of the partial view... Also the directive closure is never called.

What could I have done wrong?

**Comment by sebastiandedeyne** [comment]
What Laravel version are you on? And could you provide some more context of your view (any other directives being used nearby?)

**Comment by Lambik** [comment]
I'm on 5.1, and not really. The view is quite standard with an `@extends`, and in a `@section`.

I've been able to create my own directive, which works also.

I thought it could have been related to that view having a composer on it, but I tried another (basic) include, which also just dumped the tag instead of interpreting it.

I also cleared several caches, but that didn't seem to help (view:clear, route:clear, config:clear, cache:clear, clear-compiled).

**Comment by Lambik** [comment]
Found something more:

The PartialCacheServiceProvider gets called before rendering my view (correctly), and it sets the correct directive (I checked Blade::getCustomDirectives() after it did its ::directive line).

However, when my view gets rendered (I checked in the view composer), the call to Blade::getCustomDirectives() only returns my own directives, no longer the PartialCache one.

I wonder where that object ran off too...

**Comment by sebastiandedeyne** [comment]
Hmm, odd. When you register directives yourself, do you get the same issue?

**Comment by Lambik** [comment]
Apparently, I have to include your tool _after_ `GrahamCampbell\HTMLMin\HTMLMinServiceProvider::class`  in config/app.php. I guess that one does something to Blade that causes it to be changed, and to lose the directives...

**Comment by Lambik** [comment]
I'm sorry for wasting your time on this :-(
Thanks for the cool tool, I really needed it :-)

**Comment by sebastiandedeyne** [comment]
No problem, glad it all worked out!
