### ISSUE TITLE
Add support for Laravel 5.3

### ISSUE THREAD

**Issue by racibaz** [spatie/laravel-partialcache#6]

**Comment by freekmurze** [comment]
I don't think it'll work on L5.3 currently. The way L5.3 handles Blade directives has changed a bit.

I'd accept a PR that adds L5.3 compatiblity. L5.1, L5.2 and PHP 5 support may be dropped.

**Comment by billmn** [comment]
@oLDu67 @freekmurze I think this can be closed.
